import type { FormatHandler } from "../FormatHandler.ts";

import canvasToBlobHandler from "./canvasToBlob.ts";
import meydaHandler from "./meyda.ts";
import htmlEmbedHandler from "./htmlEmbed.ts";
import FFmpegHandler from "./FFmpeg.ts";
import pdftoimgHandler from "./pdftoimg.ts";
import ImageMagickHandler from "./ImageMagick.ts";
import curaniHandler from "./curani.ts";
import bunburrowsHandler from "./bunburrows.ts";
import rgbaHandler from "./rgba.ts";
import svgTraceHandler from "./svgTrace.ts";
import { renameZipHandler, renameTxtHandler } from "./rename.ts";
import envelopeHandler from "./envelope.ts";
import pandocHandler from "./pandoc.ts";
import svgForeignObjectHandler from "./svgForeignObject.ts";
import qoiFuHandler from "./qoi-fu.ts";
import sppdHandler from "./sppd.ts";
import threejsHandler from "./threejs.ts";
import sqlite3Handler from "./sqlite.ts";
import vtfHandler from "./vtf.ts";
import mcMapHandler from "./mcmap.ts";
import jszipHandler from "./jszip.ts";
import alsHandler from "./als.ts";
import qoaFuHandler from "./qoa-fu.ts";
import pyTurtleHandler from "./pyTurtle.ts";
import { fromJsonHandler, toJsonHandler } from "./json.ts";
import nbtHandler from "./nbt.ts";
import peToZipHandler from "./petozip.ts";
import flptojsonHandler from "./flptojson.ts";
import floHandler from "./flo.ts";
import cgbiToPngHandler from "./cgbi-to-png.ts";
import batToExeHandler from "./batToExe.ts";
import textEncodingHandler from "./textEncoding.ts";
import sb3ToHtmlHandler from "./sb3tohtml.ts";
import libopenmptHandler from "./libopenmpt.ts";
import { midiCodecHandler, midiSynthHandler } from "./midi.ts";
import lzhHandler from "./lzh.ts";
import textToGoHandler from "./textToGo.ts";
import txtToInfiniteCraftHandler from "./txtToInfiniteCraft.ts";
import wadHandler from "./wad.ts";
import espeakngHandler from "./espeakng.js"
import textToShellHandler from "./texttoshell.ts";
import exeToBatHandler from "./exeToBat.ts";
import batchHandler from "./batch.ts";
import bsorHandler from "./bsor.ts";
import txtToPyHandler from './textToPy.ts';
import fontHandler from "./font.ts";
import icnsHandler from "./icns.ts";
import mcSchematicHandler from "./mcSchematicHandler.ts";
import bsonHandler from "./bson.ts";
import asepriteHandler from "./aseprite.ts";
import csharpHandler from "./csharp.ts";
import n64romHandler from "./n64rom.ts";
import vexflowHandler from "./vexflow.ts";
import toonHandler from "./toon.ts";
import rpgmvpHandler from "./rpgmvp.ts";
import tarHandler from "./tar.ts";
import otaHandler from "./ota.ts";
import comicsHandler from "./comics.ts";
import terrariaWldHandler from "./terrariawld.ts";
import ArchiveHandler from "./archive.ts";

const handlers: FormatHandler[] = [];
try { handlers.push(new svgTraceHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new canvasToBlobHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new meydaHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new htmlEmbedHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new FFmpegHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new pdftoimgHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new ImageMagickHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new curaniHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new bunburrowsHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new rgbaHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(renameZipHandler) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(renameTxtHandler) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new envelopeHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new svgForeignObjectHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new qoiFuHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new sppdHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new threejsHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new sqlite3Handler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new vtfHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new mcMapHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new jszipHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new alsHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new qoaFuHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new pyTurtleHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new fromJsonHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new toJsonHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new nbtHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new peToZipHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new flptojsonHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new floHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new cgbiToPngHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new batToExeHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new sb3ToHtmlHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new textEncodingHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new libopenmptHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new midiCodecHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new midiSynthHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new lzhHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new wadHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new pandocHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new textToGoHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new txtToInfiniteCraftHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new espeakngHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new textToShellHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new exeToBatHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new batchHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new bsorHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new txtToPyHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new fontHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new icnsHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new mcSchematicHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new bsonHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new asepriteHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new csharpHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new n64romHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new vexflowHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new toonHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new rpgmvpHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new tarHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new otaHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new comicsHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new terrariaWldHandler()) } catch (e) { console.warn("Failed to init handler:", e); };
try { handlers.push(new ArchiveHandler()) } catch (e) { console.warn("Failed to init handler:", e); };

export default handlers;
